### ISSUE TITLE
app does not open

### ISSUE THREAD

**Issue by tzaqam** [RDE3/Mac_Spotify_Adblock#1]
the output when i try to run from terminal: 

`% /Applications/Spotify.app/Contents/MacOS/Spotify
dlopen /Applications/Spotify.app/Contents/MacOS/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework: dlopen(/Applications/Spotify.app/Contents/MacOS/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework, 0x0105): tried: '/Applications/Spotify.app/Contents/MacOS/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Library/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework' (no such file), '/System/Library/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework' (no such file), '/Applications/Spotify.app/Contents/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Library/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework' (no such file), '/System/Library/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework' (no such file)
Failed to load the CEF framework`

**Comment by RDE3** [comment]
Hey, did you follow all the steps and install the certificate before opening Spotify? I tried opening Spotify using this command "/Applications/Spotify.app/Contents/MacOS/Spotify dlopen" and it worked for me.

Try uninstalling the application and installing it again, or open Spotify directly from Launchpad.

_`Regarding this error, "mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'", if you have an M1 Mac, install arm version of Spotify.`_ 

**Edit: I fixed it, it should work now.**
