### ISSUE TITLE
Spotify fails to launch on the new version 

### ISSUE THREAD

**Issue by jimmysofat6864** [RDE3/Mac_Spotify_Adblock#11]
Hi there I noticed when installing the patch on the latest version of Spotify it fails to launch. Does anybody else here have this issue?

**Comment by ArtemisGraphic** [comment]
+1

**Comment by HatshibaInu** [comment]
+1

**Comment by Amiir97** [comment]
+1

**Comment by Syzygianinfern0** [comment]
@RDE3 did you get to check this out?

**Comment by lcaamal** [comment]
Same problem spotify crash

**Comment by deavy** [comment]
At the moment you can rollback changes to make Spotify app work again until the fix is here.
Open `Spotify.app/Contents/Frameworks/Chromium Embedded Framework.framework` folder, delete `Chromium Embedded Framework`, and rename `Chromium Embedded Framework.orig` to `Chromium Embedded Framework`.

**Comment by Sawen1981** [comment]
Hello, it works fine on version 1.1.94.870.gf994cb0b but no longer works under 1.1.95.893.g6cf4d40c sadly, it hides the banner but the vocal ads play. I how can you let say you download the working version but as soon as you launch the installer it downloads the latest. How to prevent that from happening? I wonder. Thank you. ( though when I run the cmd I get no identity found )

**Comment by Sawen1981** [comment]
Never mind I found myself what the problem was.

**Comment by ArtemisGraphic** [comment]
> Never mind I found myself what the problem was.

Willing to share?

**Comment by Sawen1981** [comment]
> 

Yup I have actually had installed another ad-block similar to this one, and another certificate needed to be created in order to have this one working. Now I wonder, if somehow the Spotify gets updated again if this block will be effective. Probably not. Hope that helps.

**Comment by Amiir97** [comment]
@RDE3 fix ETA?

**Comment by Sawen1981** [comment]
Yeah it no longer works now..

**Comment by Syzygianinfern0** [comment]
https://github.com/SpotX-CLI/SpotX-Mac

I've shifted to this for the time being.

**Comment by Sawen1981** [comment]
> https://github.com/SpotX-CLI/SpotX-Mac
> 
> I've shifted to this for the time being.

Yup, i can confirm this is perfectly working! I had seen this one, but i thought it was going to be an invasive one but nope, all good 👍

**Comment by RiotNrrrd** [comment]
Please see my comment on the more recent issue #12 about why Spotify isn't launching (and a _[spotiblock.c.patch](https://github.com/RDE3/Mac_Spotify_Adblock/files/11269239/spotiblock.c.patch)_ patch for _spotiblock.c_).

**Comment by Devanshu-17** [comment]
@jimmysofat6864 @ArtemisGraphic @HatshibaInu @Amiir97 @Syzygianinfern0 @lcaamal @deavy @Sawen1981 @RiotNrrrd 

Hey guys. Sorry for not replying earlier. I was busy irl stuff. Yes, you all are correct that this repo is no longer being maintained. However, if you all want, you can contribute to this by opening a pull request.
