### ISSUE TITLE
Every now and then Spotify suddenly starts crashing when opening, requiring a fresh install of the both Spotify and the certificate

### ISSUE THREAD

**Issue by SKDemon820** [RDE3/Mac_Spotify_Adblock#3]
I'm not sure what causes it, it seems to be random.  Usually it works fine for a week or two before happening, but just now I experienced it after only 2 days of the reinstall.  I didn't update Spotify before it happens, in fact a while ago I updated Spotify with the certificate active and it continued to work fine before the eventual random crashing.

**Comment by tzaqam** [comment]
Same here

**Comment by RDE3** [comment]
Hey, @tzaqam @SKDemon820 . You just need to reinstall the certificate whenever there is an update and rename it. There is no need to reinstall Spotify repeatedly. 

If the app crashes, just quit the app process from Activity Monitor and rename the certificate. After that, just run the command bash install.sh "new certificate name". Now your app should be working perfectly.

**Comment by RDE3** [comment]
UPDATE 2: Fixed to run on latest version. Contributed by @ptest13243546
