### ISSUE TITLE
Unable to block audio ads

### ISSUE THREAD

**Issue by nonplaybox** [RDE3/Mac_Spotify_Adblock#4]
Using this program, I successfully blocked the picture ads, but when I click on the song list, there is a box at the bottom.
And after playing the song, the audio ad still appears.
Is this an isolated case, please?
Thank you very much for your efforts!

**Comment by RDE3** [comment]
Hey, the box at the bottom will appear. However, there should be no audio ads. Can you please try and reinstall the certificate again, while renaming it.

I tried it on an intel and silicon app. It's working perfectly for the latest update 
Spotify for macOS 1.1.86.857
