### ISSUE TITLE
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

### ISSUE THREAD

**Issue by jimmysofat6864** [RDE3/Mac_Spotify_Adblock#5]
Sometimes I get this error message when trying to run the script. 

`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`

The way to fix this is to run this command. 

`xcode-select --install`

Maybe the script should run this command in case it fails or instruct the user to do so when this error message is encountered.

**Comment by RDE3** [comment]
Yes, we have to install xcode command line tools for the script to run properly. I will include this in the script which will prompt user to install xcode tools if they haven't installed it previously.
