### ISSUE TITLE
A new update for Spotify making the patching stop working

### ISSUE THREAD

**Issue by Phaminator19** [RDE3/Mac_Spotify_Adblock#8]
Please fix the issue, I've updated the Spotify, and now every time I opened the app it would crash. I've renamed the certificate name and rerun the script but it still didn't work. I've ended the process in the activity monitor before I run the script as well.

**Comment by jimmysofat6864** [comment]
> Please fix the issue, I've updated the Spotify, and now every time I opened the app it would crash. I've renamed the certificate name and rerun the script but it still didn't work. I've ended the process in the activity monitor before I run the script as well.

@Phaminator19 I also have the same issue but I found that the script linked [here](https://github.com/r1olo/spotify-adblock-macos) seems to have that issue fixed. Be sure to uninstall the old script or reinstall Spotify before proceeding or it won't work.

**Comment by r1olo** [comment]
> @Phaminator19 I also have the same issue but I found that the script linked [here](https://github.com/r1olo/spotify-adblock-macos) seems to have that issue fixed. Be sure to uninstall the old script or reinstall Spotify before proceeding or it won't work.

Not anymore. I'm sure whoever straight up copied and reuploaded my repo will fix it soon.

**Comment by Phaminator19** [comment]
> > Please fix the issue, I've updated the Spotify, and now every time I opened the app it would crash. I've renamed the certificate name and rerun the script but it still didn't work. I've ended the process in the activity monitor before I run the script as well.
> 
> @Phaminator19 I also have the same issue but I found that the script linked [here](https://github.com/r1olo/spotify-adblock-macos) seems to have that issue fixed. Be sure to uninstall the old script or reinstall Spotify before proceeding or it won't work.

Nope, the link you sent is deleted. Hopefully the OP can fix this issue

**Comment by RDE3** [comment]
Hey, everyone. Please check the installation now. The issue seems to be fixed.

UPDATE 2: Fixed to run on latest version. Contributed by @ptest13243546
